blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
	# localhost:8000/blog/
	path('',views.blog_list,name='blog_list'),
    path('<int:blog_pk>', views.blog_detail,name='blog_detail'),
    path('type/<int:type_pk>',views.blogs_with_type,name='blogs_with_type'),
    path('date/<int:year>/<int:month>',views.blogs_with_date,name='blogs_with_date'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNumExpand,ReadDetail
# Create your models here.

class BlogType(models.Model):
    type_name = models.CharField(max_length=15)
    def __str__(self):
        return self.type_name

class Blog(models.Model,ReadNumExpand):
    title = models.CharField(max_length=50)
    content = RichTextUploadingField()
    author = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    blog_type = models.ForeignKey(BlogType,on_delete=models.DO_NOTHING)
    read_details = GenericRelation(ReadDetail)
    create_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return"<Blog:%s>"%self.title

    def get_url(self):
        return reverse('blog_detail',kwargs={'blog_pk':self.pk})

    def get_email(self):
        return self.author.email

    def get_user_config(self):
        return self.author.userconfig.is_email_active

    class Meta:
        ordering = ["-create_time",]

'''
class ReadNum(models.Model):
    read_num = models.IntegerField(default=0)
    blog = models.OneToOneField(Blog,on_delete=models.DO_NOTHING)    
'''

likes/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User
# Create your models here.

class LikeRecord(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	like_time = models.DateTimeField(auto_now_add=True)

	content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type','object_id')

class LikeCount(models.Model):
	like_num = models.IntegerField(default=0)

	content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type','object_id')

blog/views.py
#coding:UTF-8
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
from mysite.settings import NUMBER_OF_BLOGS_PER_PAGE
from read_statistics.utils import read_statistics_read_once
from .models import Blog,BlogType
from comment.models import Comment
from comment.forms import CommentForm
# Create your views here.
def get_blog_common_data(request,blogs_all_list):
	paginator = Paginator(blogs_all_list,NUMBER_OF_BLOGS_PER_PAGE) #分页器，每一页NUMBER_OF_BLOGS_PER_PAGE篇blog
	page_num = request.GET.get('page',1) #从GET请求获得页面参数，若无则为1
	page_of_blogs = paginator.get_page(page_num) #从分页器获取page_num页的所有blog
	current_page_num = page_of_blogs.number #当前页面
	page_range = list(range(max(1,current_page_num-2),min(paginator.num_pages,current_page_num+2)+1))

	if paginator.num_pages!=1:
	#显示首页和尾页
		if page_range[0]!=1:
			page_range.insert(0,1)
		if page_range[-1]!=paginator.num_pages:
			page_range.append(paginator.num_pages)
	#加入...
		if page_range[1]-1>1:
			page_range.insert(1,'...')
		if paginator.num_pages-page_range[-2]>1:
			page_range.insert(-1,'...')

	#blog_types = BlogType.objects.all()

	#显示博客分类中每一分类对应的博客数
	blog_types = BlogType.objects.annotate(blog_count=Count('blog'))
	#显示日期归档中每一日期所对应的博客数
	blog_dates_list={}
	for blog_date in Blog.objects.dates('create_time','month',order='DESC'):
		blog_dates_list[blog_date] = Blog.objects.all().filter(	create_time__year=blog_date.year,
																create_time__month=blog_date.month).count()
	blog_dates = Blog.objects.dates('create_time','month',order='DESC')
	context = {}
	context['page_of_blogs'] = page_of_blogs
	context['page_range'] = page_range
	context['blog_dates'] = blog_dates_list
	context['blog_types'] = blog_types
	return context

def blog_list(request):
	blogs_all_list = Blog.objects.all() #获取所有blog
	context = get_blog_common_data(request,blogs_all_list)
	return render(request,'blog/blog_list.html',context)

def blog_detail(request,blog_pk):
    blog = get_object_or_404(Blog,pk=blog_pk)

    read_cookie_key=read_statistics_read_once(request,blog)

    #blog_content_type = ContentType.objects.get_for_model(blog)
    #comments = Comment.objects.filter(object_id=blog.pk,content_type = blog_content_type,root=None)

    previous_blog = Blog.objects.filter(create_time__gt=blog.create_time).last()
    next_blog = Blog.objects.filter(create_time__lt=blog.create_time).first()
    context = {}
    context['blog'] = blog
    context['previous_blog'] = previous_blog
    context['next_blog'] = next_blog
    context['user'] = request.user
    #context['comments'] = comments.order_by('-date')
    #context['comment_form'] = CommentForm(initial={'content_type':blog_content_type.model,'object_id':blog.pk,'reply_comment_id':0})
    response = render(request,'blog/blog_detail.html',context)
    response.set_cookie(read_cookie_key,'true')
    return response
    
def blogs_with_type(request,type_pk):
	type_name = get_object_or_404(BlogType,pk=type_pk)
	blogs_all_list = Blog.objects.filter(blog_type=type_name) #获取所有blog
	context = get_blog_common_data(request,blogs_all_list)
	context['type_name'] = type_name
	return render(request,'blog/blogs_with_type.html',context)

def blogs_with_date(request,year,month):
	blogs_all_list = Blog.objects.filter(create_time__year = year,create_time__month=month) #获取所有blog
	context = get_blog_common_data(request,blogs_all_list)
	context['blog_date'] = '%s年%s月'%(year,month)
	return render(request,'blog/blogs_with_date.html',context)

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title%}
博客 {{blog.title}}
{% endblock %}

{% block nav_blog_active %}
	active
{% endblock%}

{% load staticfiles %}
{% load comment_tags %}
{% load like_tags %}
{% block header_extends %}
	<link rel="stylesheet" href="{% static 'blog/blog.css' %}">
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-10">
			<div class="panel panel-info">
			  <div class="panel-heading">
			    <div class="panel-title">
			    	<h3>{{blog.title}}</h3>
					<ul class="blog-info-description panel-title">
						<li><span class="label label-default">作者</span>
							<span class="glyphicon glyphicon-user"></span>
							<a href="{% url 'user_info' blog.author.pk %}">{{blog.author}}</a>
						</li>
						<li><span class="label label-default">分类</span>
							<span class="glyphicon glyphicon-tag"></span>
							<a href = "{% url 'blogs_with_type' blog.blog_type.pk%}">
								{{blog.blog_type}}
							</a>
						</li>
						<li><span class="label label-default">创建时间</span>
							<span class="glyphicon glyphicon-time"></span>{{blog.create_time|date:"Y-m-d H:i:s"}}
						</li>
						<li>
							<span class="label label-default">阅读次数</span>
							<span class="glyphicon glyphicon-sunglasses"></span>({{blog.get_read_num}})
						</li>  
						<li>
							<span class="label label-default">评论次数</span>
							<span class="glyphicon glyphicon-list-alt"></span>({% get_comment_count blog %})
						</li> 
					</ul>
		      	</div>
		 	</div>
			  <div class="blog-content panel-body">
			    {{blog.content|safe}}
			  </div>
		</div>
			<div class="like" onclick="likeChange(this,'{% get_content_type blog %}',{{ blog.pk }})">
				<span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %}"></span>
				<span class="liked-num">{% get_like_count blog %}</span>
				<span>like</span>
			</div>
			<div class="blog-more">
				{% if previous_blog %}
				<p>上一篇:<a href="{% url 'blog_detail' previous_blog.pk%}">{{previous_blog.title}}</a></p>
				{% else %}
				<p>上一篇:暂无博客</p>
				{% endif %}
				{% if next_blog %}
				<p>下一篇:<a href="{% url 'blog_detail' next_blog.pk%}">{{next_blog.title}}</a></p>
				{% else %}
				<p>下一篇:暂无博客</p>
				{% endif %}
			</div>
			</div>
		</div>
	</div>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<div class="comment-area">
	<h3 class="comment-area-title">提交评论</h3>
	{% if user.is_authenticated%}
		<form id="comment_form" action="{% url 'update_comment' %}" method="post" style="overflow:hidden">
 		{% csrf_token %}
 			<label for="comment_text">{{ user.username }},欢迎评论</label>
 			<div id="reply_content_container" style="display:none;">
 				<p>回复:</p>
 				<div id="reply_content">

 				</div>
 			</div>
 			{% get_comment_form blog as comment_form%}
 			{{ comment_form }}
 			<span id="comment_error" class="text-danger pull-left"></span>
		<input type="submit" value="评论" class="btn btn-primary pull-right">
		</form>
	{% else %}
		<p>未登录，登录后才能评论</p>
			<a class = "btn btn-primary"href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
			or
			<a class = "btn btn-danger" href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
	{% endif %}
	</div>
	<div class="comment-area">
	<h3 class="comment-area-title">评论列表</h3>

			<div id="comment_list">
			{% get_comments blog as comments%}
			{% for comment in comments %}

			<div id = "root_comment_{{ comment.pk }}" class="comment">	
				<div class="panel panel-primary">
				  <div class="panel-heading">
				    <h3 class="panel-title">
				    	<span>{{comment.author.get_username_or_nickname}}</span>
						<span>({{ comment.date|date:"Y-m-d H:i:s"}}):</span>
				    </h3>
				  </div>
				  <div id="comment_{{ comment.pk }}" class="panel-body">
				    {{ comment.text|safe }}
				  </div>
				</div>
				<div class="like" onclick="likeChange(this,'{% get_content_type comment %}',{{ comment.pk }})">
					<span class="glyphicon glyphicon-thumbs-up {% get_like_status comment %}"></span>
					<span class="liked-num">{% get_like_count comment %}</span>
				</div>
				{% if user.is_authenticated %}
					<a href="javascript:reply({{ comment.pk }},'true')">回复</a>
				{% else %}
					<a href="javascript:reply({{ comment.pk }},'false')">回复</a>
				{% endif %}


				{% for reply in comment.root_comment.all %}
					<div class="reply">
					<div class="panel panel-info">
						  <div class="panel-heading">
						    <h3 class="panel-title">
								<span>{{reply.author.get_username_or_nickname}}</span>
								<span>({{ reply.date|date:"Y-m-d H:i:s"}})回复</span>
								<span>{{reply.reply_to.get_username_or_nickname}}:</span>
						    </h3>
						  </div>
						  <div id="reply_{{ reply.pk }}" class="panel-body">
								{{ reply.text|safe }}
						  </div>
						</div>
					<div class="like" onclick="likeChange(this,'{% get_content_type reply %}',{{ reply.pk }})">
						<span class="glyphicon glyphicon-thumbs-up {% get_like_status reply %}"></span>
						<span class="liked-num">{% get_like_count reply %}</span>
					</div>
					{% if user.is_authenticated %}
						<a href="javascript:reply({{ reply.pk }},'true')">回复</a>
					{% else %}
						<a href="javascript:reply({{ reply.pk }},'false')">回复</a>
					{% endif %}
				{% empty %}
				{% endfor %}
				
			</div>
			{% empty %}
			<span id="no_comment" class="text-danger">暂无评论</span>
			{% endfor %}

		</div>
	</div>
</div>
{% endblock %}
{% block script_extends %}
	<script type="text/javascript">
		String.prototype.format = function(){
			var str = this;
			for (var i = 0; i < arguments.length;i++){
				var str = str.replace(new RegExp('\\{' + i + '\\}','g'),arguments[i])
			};
			return str;
		}
		$("#comment_form").submit(function(){
			$("#comment_error").text('')
			//判断是否为空
			if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
				$("#comment_error").text('评论内容不能为空');
				return false;
			}
			//更新数据到textarea
			CKEDITOR.instances['id_text'].updateElement();
			//异步提交
			$.ajax({
				url:"{% url 'update_comment' %}",
				type:'POST',
				data:$(this).serialize(),
				cache:false,
				success:function(data){
					console.log(data);
					if(data['status']=="SUCCESS"){
						if($('#reply_comment_id').val()=='0'){
							//插入评论
							var comment_html = 
							'<div id = "root_comment_{0}" class="comment">'+
								'<div class="panel panel-primary">'+	
									'<div class="panel-heading">'+
										'<h3 class="panel-title">'+
											'<span>{1}</span>'+
											'<span>({2}):</span></h3></div>'+
											'<div id="comment_{0}" class="panel-body">{3}</div></div>'+
									'<div class="like" onclick="likeChange(this,\'{4}\',{0})">'+
										'<span class="glyphicon glyphicon-thumbs-up"></span>'+
										'<span class="liked-num">0	</span>'+
									'</div>'+
									'<a href="javascript:reply({0},\'true\')">回复</a>' +
							'</div>';

							comment_html = comment_html.format(data['pk'],data['username'],data['date'],data['text'],data['content_type'],);
							$("#comment_list").prepend(comment_html);
						}else{
							//插入回复
							var reply_html = 
							'<div class="reply">' +
								'<div class="panel panel-info">' +
	                            	'<div class="panel-heading">'
									'<h3 class="panel-title">' +
									'<span>{1}</span>' +
									'<span>({2})回复</span>' +
									'<span>{4}:</span></h3></div>' +
									'<div id="comment_{0}" class="panel-body">{3}</div></div>' +			
								'<div class="like" onclick="likeChange(this,\'{5}\',{0})">' +
									'<span class="glyphicon glyphicon-thumbs-up"></span>' +
									'<span class="liked-num">0	</span>' +
								'</div>' +
								'<a href="javascript:reply({0},\'true\')">回复</a>' +
							'</div>';
							reply_html = reply_html.format(data['pk'],data['username'],data['date'],data['text'],data['reply_to'],data['content_type']);
							$("#reply_" + data['pk']).append(reply_html);
						}
						//清空编辑框的内容
						CKEDITOR.instances['id_text'].setData('');
						$('#reply_content_container').hide();
						$('#reply_comment_id').val('0');
						$("#no_comment").remove()	
					}
					else{					
						//显示错误信息
						$("#comment_error").text(data['message']);

					}
				},
				error:function(xhr){
					console.log(xhr);
				}
			});
			return false;
		});
		function reply(reply_comment_id,is_authenticated){
			console.log(is_authenticated);
			if(is_authenticated=='true'){
				
				$('#reply_comment_id').val(reply_comment_id);
				var html = $("#comment_" + reply_comment_id).html();
				$('#reply_content').html(html);
				$('#reply_content_container').show();
				$('html').animate({scrollTop: $('#comment_form').offset().top - 60},300,function(){
				CKEDITOR.instances['id_text'].focus();});
				
				//console.log('here');
				//id = "reply_form_" + reply_comment_id;
				//document.getElementById("reply_btn_"+reply_comment_id).style.display = "none";
				//document.getElementById("reply_form_"+reply_comment_id).style.display = "";
				//var reply_container = 
				//'<form ' +
				//'id="comment_form" action="{0}" method="post"style="overflow:hidden">' +
 				//'{1}' +
 				//'{2}' +
 				//'<label for="comment_text">{{ user.username }},欢迎评论</label>' +
 				//'{3}' +
 				//'<span id="comment_error" class="text-danger pull-left"></span>' +
				//'<input type="submit" value="评论" class="btn btn-primary pull-right">' +
				//'</form>';
				//$("#"+id).append(reply_container);
			}
			else{
				$('#login_modal').modal('show');
			}

		}
		function likeChange(obj,content_type,object_id){
			var is_liked = obj.getElementsByClassName('active').length == 0
			$.ajax({
				url:"{% url 'like_change' %}",
				type:'GET',
				data:{
					content_type:content_type,
					object_id:object_id,
					is_liked:is_liked,
				},
				cache:false,
				success:function(data){
					console.log(data);
					if (data['status'] == 'SUCCESS'){
						//更新点赞状态
						var like_status = $(obj.getElementsByClassName('glyphicon'));
						if (is_liked){
							//点赞
							like_status.addClass('active');
						}
						else{
							//取消点赞
							like_status.removeClass('active');
						}
						//更新点赞数量
						var like_num = $(obj.getElementsByClassName('liked-num'));
						like_num.text(data['like_num'])

					}
					else{
						if (data['code'] == '399'){
							$('#login_modal').modal('show')
						}
						else{alert(data['message'])}
					}
				},
				error:function(xhr){
					console.log(chr);
				}
			});

		}
	</script>





{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title%}
博客列表
{% endblock %}

{% block nav_blog_active %}
	active
{% endblock%}

{% load staticfiles %}
{% load comment_tags %}
{% load like_tags %}
{% block header_extends %}
	<link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
			<div class="panel panel-default">
				<div class="panel-heading">{% block blog_list_title %}博客列表
					{% endblock %}</div>
  				<div class="panel-body">
    				{% for blog in page_of_blogs %}
    					<div class="blog">
							<h3><a href="{% url 'blog_detail' blog.pk%}">{{blog.title}}</a></h3>
							<p class="classinfo">
								<span class="glyphicon glyphicon-tag"></span><a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>
								<span class="glyphicon glyphicon-time"></span>{{ blog.create_time|date:"Y-m-d H:i:s"}}
                <span class="glyphicon glyphicon-sunglasses"></span>阅读数({{blog.get_read_num}})
                <span class="glyphicon glyphicon-list-alt"></span>评论数({% get_comment_count blog %})
                <span class="glyphicon glyphicon-thumbs-up"></span>点赞数({% get_like_count blog %})
							</p>
						</div>
					{% empty %}
						<div class="blog">
							<p>暂无博客，敬请期待</p>
						</div>
					{% endfor %}
  				</div>
			</div>
  				<ul class="pagination">
    				<li>
    					{% if page_of_blogs.has_previous%}
      						<a href="?page={{page_of_blogs.previous_page_number}}" aria-label="Previous">
        					<span aria-hidden="true">&laquo;</span>
      						</a>
      					{% else %}
      						<span aria-hidden="true">&laquo;</span>
      					{% endif %}
    				</li>
    				<li>
    					{% for page_num in page_range %}
    					{% if page_num == page_of_blogs.number%}
    						<li class="active"><a>{{page_num}}</a></li>
    					{% elif page_num == '...' %}
    						<li><a>{{page_num}}</a></li>
    					{% else %}
    						<li><a href="?page={{page_num}}">{{page_num}}</a></li>
    					{% endif %}
    					{% endfor %}
    				</li>
    				<li>
    					{% if page_of_blogs.has_next%}
      						<a href="?page={{page_of_blogs.next_page_number}}" aria-label="Next">
        					<span aria-hidden="true">&raquo;</span>
      						</a>
      					{% else %}
      						<span aria-hidden="true">&raquo;</span>
      					{% endif %}
    				</li>
  				</ul>
  				<p>共{{page_of_blogs.paginator.count}}篇博客 {{page_of_blogs.number}}页/{{page_of_blogs.paginator.num_pages}}页</p>
		</div>
		<div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
			<div class="panel panel-default">
  				<div class="panel-heading">博客分类</div>
  				<div class="panel-body">
    				<ul class="blog-types">
						{% for blog_type in blog_types %}
							<li>
								<a href="{% url 'blogs_with_type' blog_type.pk %}">
									{{blog_type.type_name}} ({{blog_type.blog_count}})
								</a>
							</li>
						{% empty %}
							<li>
								暂无分类
							</li>

						{% endfor %}
					</ul>
  				</div>
			</div>
      <div class="panel panel-default">
          <div class="panel-heading">日期归档</div>
          <div class="panel-body">
            <ul class="blog-dates">
            {% for blog_date,blog_count in blog_dates.items %}
              <li>
                <a href="{% url 'blogs_with_date' blog_date.year blog_date.month %}">
                  {{blog_date|date:"Y年m月"}} ({{blog_count}})
                </a>
              </li>
            {% empty %}
              <li>
                暂无日期归档
              </li>
            {% endfor %}
          </ul>
          </div>
      </div>
		</div>
	</div>
</div>

{% endblock %}

blog/templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html' %}

{% block title%}
日期归档:{{blog_date}}
{% endblock %}

{% block blog_list_title %}
日期归档:{{blog_date}}
<a href="{% url 'blog_list' %}">查看全部博客</a>
{% endblock %}

blog/templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}

{% block title%}
博客分类:{{type_name}}
{% endblock %}

{% block blog_list_title %}
分类:{{type_name}}
<a href="{% url 'blog_list' %}">查看全部博客</a>
{% endblock %}

blog/templates/blog/test.html
<tr><th></th><td><div class="django-ckeditor-widget" data-field-id="id_text" style="display: inline-block;">
    <textarea cols="40" id="id_text" name="text" rows="10" required data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;custom&quot;, &quot;height&quot;: &quot;180&quot;, &quot;width&quot;: &quot;auto&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;toolbar_custom&quot;: [[&quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;Subscript&quot;, &quot;Superscript&quot;], [&quot;TextColor&quot;, &quot;BGCOlor&quot;, &quot;RemoveFormat&quot;], [&quot;NumberedList&quot;, &quot;BulletedList&quot;], [&quot;Link&quot;, &quot;Unlink&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;, &quot;Blockquote&quot;]], &quot;tabSpaces&quot;: 4, &quot;removePlugins&quot;: &quot;elementspath&quot;, &quot;resize_enabled&quot;: false, &quot;language&quot;: &quot;zh-cn&quot;}" data-external-plugin-resources="[]" data-id="id_text" data-type="ckeditortype"></textarea>
</div><input type="hidden" name="content_type" value="blog" id="id_content_type"><input type="hidden" name="object_id" value="40" id="id_object_id"><input type="hidden" name="reply_comment_id" value="0" id="reply_comment_id"></td></tr>